### ISSUE TITLE
Management of TLS site configuration

### ISSUE THREAD

**Issue by blackknight36** [jflorian/doubledog-apache#2]
I'd like to update this module to allow management of TLS enabled sites.  Do you think it would be better to update the apache::site_config type to allow this or should there be a separate apache::ssl_site_config type?  apache::ssl_site_config essentially duplicates the site_config class with a few new parameters to allow management of the TLS key data.  For example, see the manifest file located at https://github.com/blackknight36/puppet-apache/blob/master/manifests/ssl_site_config.pp.

**Comment by jflorian** [comment]
Thus far I've used a combination of `apache::site_config{'ssl'}: content => ...` and `openssl::tls_certificate`.

My preference is to only have one module deploying certificates for the simple reason that they're so essential to security that I prefer to only have to audit/scrutinize one module for their management.  Admittedly this leads to module dependencies which limits flexibility with Puppet's current limitations.  I'm hopeful they'll improve this soon because I'm also an ardent believer in [the DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

However, it's not hard to see that my method of managing `ssl.conf` is sub-optimal.  Perhaps my biggest offense is mingling `VirtualHost` sections within the `ssl.conf` that RedHat/Fedora ships, though they themselves pretty much promote that with the default.  Ideally, that file would be left as shipped in the rpm and individual `apache::site_config` (or as you mentioned, `apache::ssl_site_config`) would cover the rest.  That then begs the Q, should the `SSLCertificateFile` and `SSLCertificateKeyFile` in the default `ssl.conf` be neutered somehow?  Can each `VirtualHost` have its own cert/key pair?

I definitely think that the "SSL site" files should have very few `SSL*` settings in them so that those can be delegated to the *one* `ssl.conf` provided by the rpm.  I don't think this module should get concerned with things like `SSLCipherSuite`.  The overarching design goal of this module vs most others, especially the beast for PuppetLabs (or Voxpupuli?) is that it tends to leave most things "as shipped" and merely adds onto that rather than replacing what was shipped.  (I have more trust in the packagers understanding the security ramifications than I do of the average Puppet module maintainer.)

**Comment by blackknight36** [comment]
> Thus far I've used a combination of apache::site_config{'ssl'}: content => ... and openssl::tls_certificate.

That's pretty much what I'm doing with the current release of this module, file resources for the certificate data and an apache::site_config resource for the vhost configuration.  This works well but having one meta type which handles everything is nice to have.

Normally I do not mess with the ssl.conf file as that is a vendor provided file and the settings in that file only apply to the default virtual host.  Apache does allow each vhost to provide its own SSL options along with their own key pair using SNI but I do not have any servers that use this feature.

I'll leave this alone for now since I can accomplish what I need using other methods.
